/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    offers: Offer;
    sections: Section;
    manufacturers: Manufacturer;
    publications: Publication;
    media: Media;
    'exchange-rates': ExchangeRate;
    users: User;
    orders: Order;
    conversations: Conversation;
    'crm-deliveries': CrmDelivery;
    'import-runs': ImportRun;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    manufacturers: ManufacturersSelect<false> | ManufacturersSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'exchange-rates': ExchangeRatesSelect<false> | ExchangeRatesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    conversations: ConversationsSelect<false> | ConversationsSelect<true>;
    'crm-deliveries': CrmDeliveriesSelect<false> | CrmDeliveriesSelect<true>;
    'import-runs': ImportRunsSelect<false> | ImportRunsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'pricing-settings': PricingSetting;
    'site-settings': SiteSetting;
    'home-page': HomePage;
  };
  globalsSelect: {
    'pricing-settings': PricingSettingsSelect<false> | PricingSettingsSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  status: 'draft' | 'published';
  slug: string;
  kind: 'software' | 'hardware' | 'course' | 'service';
  summary?: string | null;
  description?: string | null;
  manufacturer?: (number | null) | Manufacturer;
  sections?: (number | Section)[] | null;
  tasks?:
    | {
        title: string;
        id?: string | null;
      }[]
    | null;
  requiresProducts?: (number | Product)[] | null;
  recommended?: (number | Product)[] | null;
  gallery?: (number | Media)[] | null;
  properties?:
    | {
        name: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  legacyKey?: string | null;
  legacyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers".
 */
export interface Manufacturer {
  id: number;
  title: string;
  status: 'draft' | 'published';
  website?: string | null;
  legacyKey?: string | null;
  legacyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: number;
  title: string;
  status: 'draft' | 'published';
  slug: string;
  parent?: (number | null) | Section;
  isDirection?: boolean | null;
  menuGroup: 'software' | 'hardware' | 'service';
  summary?: string | null;
  icon?:
    | (
        | 'building'
        | 'columns'
        | 'layers'
        | 'route'
        | 'wrench'
        | 'droplet'
        | 'cog'
        | 'image'
        | 'file'
        | 'scan'
        | 'printer'
        | 'monitor'
        | 'graduation'
      )
    | null;
  tone?: ('navy' | 'blue' | 'graphite') | null;
  order?: number | null;
  legacyKey?: string | null;
  legacyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  legacyKey?: string | null;
  legacyUrl?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  status: 'draft' | 'published';
  product?: (number | null) | Product;
  configuration: string;
  license: string;
  amount: string;
  currency: 'KZT' | 'USD' | 'EUR' | 'RUB';
  includesVat?: boolean | null;
  sourceVat: string;
  legacyKey?: string | null;
  legacyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  status: 'draft' | 'published';
  slug: string;
  kind: 'article' | 'news' | 'promotion';
  excerpt?: string | null;
  topic?: string | null;
  body?: string | null;
  cover?: (number | null) | Media;
  publishedAt?: string | null;
  legacyKey?: string | null;
  legacyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rates".
 */
export interface ExchangeRate {
  id: number;
  currency: 'USD' | 'EUR' | 'RUB';
  kztPerUnit: string;
  effectiveAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  number: string;
  mode: 'demo' | 'live';
  buyerType: 'individual' | 'company';
  contactName: string;
  contactPhone: string;
  contactEmail: string;
  companyName?: string | null;
  bin?: string | null;
  comment?: string | null;
  totalKzt: string;
  consent?: {
    accepted?: boolean | null;
    at?: string | null;
    version?: string | null;
    text?: string | null;
  };
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  idempotencyKey: string;
  fingerprint: string;
  clientHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations".
 */
export interface Conversation {
  id: number;
  idempotencyKey: string;
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  state: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-deliveries".
 */
export interface CrmDelivery {
  id: number;
  idempotencyKey: string;
  order?: (number | null) | Order;
  state: 'pending' | 'processing' | 'not-sent-demo' | 'sent' | 'failed' | 'dead';
  attempts?: number | null;
  nextAttemptAt?: string | null;
  ambiguous?: boolean | null;
  lastError?: string | null;
  externalId?: string | null;
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs".
 */
export interface ImportRun {
  id: number;
  idempotencyKey: string;
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  state: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  from: string;
  to: string;
  legacyKey?: string | null;
  legacyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'sections';
        value: number | Section;
      } | null)
    | ({
        relationTo: 'manufacturers';
        value: number | Manufacturer;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'exchange-rates';
        value: number | ExchangeRate;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'conversations';
        value: number | Conversation;
      } | null)
    | ({
        relationTo: 'crm-deliveries';
        value: number | CrmDelivery;
      } | null)
    | ({
        relationTo: 'import-runs';
        value: number | ImportRun;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  slug?: T;
  kind?: T;
  summary?: T;
  description?: T;
  manufacturer?: T;
  sections?: T;
  tasks?:
    | T
    | {
        title?: T;
        id?: T;
      };
  requiresProducts?: T;
  recommended?: T;
  gallery?: T;
  properties?:
    | T
    | {
        name?: T;
        value?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  legacyKey?: T;
  legacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  product?: T;
  configuration?: T;
  license?: T;
  amount?: T;
  currency?: T;
  includesVat?: T;
  sourceVat?: T;
  legacyKey?: T;
  legacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  slug?: T;
  parent?: T;
  isDirection?: T;
  menuGroup?: T;
  summary?: T;
  icon?: T;
  tone?: T;
  order?: T;
  legacyKey?: T;
  legacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturers_select".
 */
export interface ManufacturersSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  website?: T;
  legacyKey?: T;
  legacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  slug?: T;
  kind?: T;
  excerpt?: T;
  topic?: T;
  body?: T;
  cover?: T;
  publishedAt?: T;
  legacyKey?: T;
  legacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  legacyKey?: T;
  legacyUrl?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exchange-rates_select".
 */
export interface ExchangeRatesSelect<T extends boolean = true> {
  currency?: T;
  kztPerUnit?: T;
  effectiveAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  mode?: T;
  buyerType?: T;
  contactName?: T;
  contactPhone?: T;
  contactEmail?: T;
  companyName?: T;
  bin?: T;
  comment?: T;
  totalKzt?: T;
  consent?:
    | T
    | {
        accepted?: T;
        at?: T;
        version?: T;
        text?: T;
      };
  snapshot?: T;
  idempotencyKey?: T;
  fingerprint?: T;
  clientHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "conversations_select".
 */
export interface ConversationsSelect<T extends boolean = true> {
  idempotencyKey?: T;
  snapshot?: T;
  state?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crm-deliveries_select".
 */
export interface CrmDeliveriesSelect<T extends boolean = true> {
  idempotencyKey?: T;
  order?: T;
  state?: T;
  attempts?: T;
  nextAttemptAt?: T;
  ambiguous?: T;
  lastError?: T;
  externalId?: T;
  snapshot?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "import-runs_select".
 */
export interface ImportRunsSelect<T extends boolean = true> {
  idempotencyKey?: T;
  snapshot?: T;
  state?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  legacyKey?: T;
  legacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-settings".
 */
export interface PricingSetting {
  id: number;
  vat: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  phones?:
    | {
        label: string;
        tel: string;
        id?: string | null;
      }[]
    | null;
  whatsapp?: string | null;
  telegram?: string | null;
  email?: string | null;
  socials?:
    | {
        network: 'instagram' | 'facebook' | 'youtube' | 'telegram' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  footerText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  eyebrow?: string | null;
  title: string;
  sideCards?:
    | {
        title: string;
        text?: string | null;
        linkLabel?: string | null;
        linkHref?: string | null;
        dark?: boolean | null;
        id?: string | null;
      }[]
    | null;
  bim?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    stages?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
    linkLabel?: string | null;
    linkHref?: string | null;
  };
  process?:
    | {
        title: string;
        text?: string | null;
        id?: string | null;
      }[]
    | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    title?: string | null;
    text?: string | null;
    linkLabel?: string | null;
    linkHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-settings_select".
 */
export interface PricingSettingsSelect<T extends boolean = true> {
  vat?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phones?:
    | T
    | {
        label?: T;
        tel?: T;
        id?: T;
      };
  whatsapp?: T;
  telegram?: T;
  email?: T;
  socials?:
    | T
    | {
        network?: T;
        url?: T;
        id?: T;
      };
  footerText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  eyebrow?: T;
  title?: T;
  sideCards?:
    | T
    | {
        title?: T;
        text?: T;
        linkLabel?: T;
        linkHref?: T;
        dark?: T;
        id?: T;
      };
  bim?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        stages?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        linkLabel?: T;
        linkHref?: T;
      };
  process?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        text?: T;
        linkLabel?: T;
        linkHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}