'use client'
import { useState } from 'react'
import Link from 'next/link'
import { demoProducts } from '@/domain/demo'
export function Configurator({ product }: { product: typeof demoProducts[number] }) {
  const [offerId, setOffer] = useState(product.offers[0].id), [quantity, setQuantity] = useState(1), [result, setResult] = useState(''), [busy, setBusy] = useState(false)
  async function calculate() { setBusy(true); setResult(''); try { const response = await fetch('/api/quote', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ offerId, quantity }) }); const data = await response.json(); setResult(response.ok ? `${new Intl.NumberFormat('ru-KZ').format(BigInt(data.totalKzt))} ₸ · учебная цена, с НДС 16%` : data.error) } catch { setResult('Не удалось рассчитать цену. Попробуйте ещё раз.') } finally { setBusy(false) } }
  return <div className="config"><label>Комплектация<select value={offerId} onChange={e => { setOffer(e.target.value); setResult('') }}>{product.offers.map(o => <option key={o.id} value={o.id}>{o.title}</option>)}</select></label><label>Количество<input type="number" min="1" max="999" value={quantity} onChange={e => { setQuantity(Number(e.target.value)); setResult('') }}/></label><button disabled={busy} onClick={calculate}>{busy ? 'Расчёт…' : 'Рассчитать цену'}</button><p role="status">{result}</p></div>
}
export default function Catalog() {
  const [direction, setDirection] = useState(''), [manufacturer, setManufacturer] = useState(''), [task, setTask] = useState(''), [selected, setSelected] = useState<typeof demoProducts[number] | null>(null)
  const scope = demoProducts.filter(p => !direction || p.direction === direction)
  const products = scope.filter(p => (!manufacturer || p.manufacturer === manufacturer) && (!task || p.task === task))
  return <section id="catalog"><div className="section-title"><div><p className="eyebrow">КАТАЛОГ</p><h2>Решения под вашу задачу</h2></div><span>03 демонстрационных решения</span></div><div className="directions">{['', ...new Set(demoProducts.map(p => p.direction))].map(d => <button key={d} aria-pressed={direction === d} className={direction === d ? 'active' : 'secondary'} onClick={() => { setDirection(d); setManufacturer(''); setTask('') }}>{d || 'Все направления'}</button>)}</div><div className="filters"><label>Производитель<select value={manufacturer} onChange={e => setManufacturer(e.target.value)}><option value="">Все производители</option>{[...new Set(scope.map(p => p.manufacturer))].map(m => <option key={m}>{m}</option>)}</select></label><label>Задача<select value={task} onChange={e => setTask(e.target.value)}><option value="">Все задачи</option>{[...new Set(scope.map(p => p.task))].map(t => <option key={t}>{t}</option>)}</select></label></div><div className="grid">{products.map((p, index) => <article className="card" key={p.id}><div className="product-art" aria-hidden="true">{['▱', '◇', '⌖'][index]}</div><small>{p.direction}</small><h3><Link href={`/products/${p.id}`}>{p.title}</Link></h3><p>{p.description}</p><button className="secondary" onClick={() => setSelected(p)}>Быстрый просмотр ↗</button></article>)}</div>{!products.length && <p>По выбранным фильтрам решений нет.</p>}{selected && <div className="preview"><div className="section-title"><h3>{selected.title}</h3><button className="secondary" onClick={() => setSelected(null)}>Закрыть</button></div><Configurator key={selected.id} product={selected}/><Link href={`/products/${selected.id}`}>Полная страница →</Link></div>}</section>
}

